### ISSUE TITLE
Generate languages translation files

### ISSUE THREAD

**Issue by brashrebel** [dragonslayerindustries/learndash-mailchimp#14]
I have a license for POEdit so I could maybe do this. But we need to ensure all strings are translatable and that before deploying there is a .pot file as well as .po and .mo files.

**Comment by objectsweb** [comment]
Done.

**Comment by brashrebel** [comment]
I don't see the translation files. There's an empty /languages folder but no files.

**Comment by objectsweb** [comment]
- Kindly upload the below template into translation program such as Poedit in order to generate .mo and .po files 
- Select the language that you want
- Generate .mo and .po files 
- Add .mo and .po files into languages file with .pot (.pot file already added)
- Ensure that files follow the following structure [@plugin name-language code lower case_ language code uppercase ]:
> Example 
> > learndash-mailchimp-en_EN.po
> > learndash-mailchimp-en_EN.mo 

**Template URL:** https://drive.google.com/file/d/0BxEM6iZoMCrrYnJ5WldpU1F1eXc/view?usp=sharing

**Comment by d4mation** [comment]
A lot of stuff was untranslatable, but this has been fixed.
