### ISSUE TITLE
What does "During the course" do?

### ISSUE THREAD

**Issue by brashrebel** [dragonslayerindustries/learndash-mailchimp#22]
When editing the course, there's a MailChimp related checkbox called "During the course" but I can't figure out what this does. I went into a course as a new user and completed a lesson but didn't see any subscribe checkbox.

**Comment by brashrebel** [comment]
Actually I can't figure out what "After completing the course" does either. When does that show something?

**Comment by objectsweb** [comment]
Please check point #19 comment.

**Comment by brashrebel** [comment]
I've been testing this but I cannot get the subscribe form to appear _during_ the course. I have the setting checked but I click "Take this course" and go through lessons and assignments but never see the subscribe form. Where should it be appearing?

**Comment by objectsweb** [comment]
Did you made all checks in point #15 as below:

Please ensure that the short code is as following:
[learndash_mc] --> at course page
[learndash_mc course_id="1"] --> at any other page
Kindly check that auto subscribe checkbox not checked, because if it check no subscribe button will appear

Kindly check that course price type is free

Kindly check if you are admin or not because admin as you know have access for all courses so he/ she will not see take this course button

**Comment by brashrebel** [comment]
I just tested again and verified all these things. I started the course and went to complete some lessons and assignments but could not see any subscribe form. Where should it be appearing?

**Comment by objectsweb** [comment]
I'll pass to you a video record that describe the whole process from scratch in order to try it yourself. 

Thanks you,

**Comment by objectsweb** [comment]
- Please check the video in the following link:
https://drive.google.com/file/d/0BxEM6iZoMCrrQkdhak80TDRZZjA/view?usp=sharing

Thank you.

**Comment by brashrebel** [comment]
This seems to be working.
