### ISSUE TITLE
Activating LearnDash results in PHP fatal error

### ISSUE THREAD

**Issue by brashrebel** [dragonslayerindustries/learndash-mailchimp#29]
Everything was working great until I re-activated LearnDash. I had deactivated LearnDash while leaving this plugin active and observed that #13 is working great. Then I activated LearnDash again and got this PHP error:

> Fatal error: Cannot redeclare class nss_plugin_updater_sfwd_lms in /Users/kylemaurer/Documents/Websites/plugins.dev/wp-content/plugins/learndash/includes/ld-autoupdate.php on line 12.

**Comment by objectsweb** [comment]
For this error " Fatal error: Cannot redeclare class nss_plugin_updater_sfwd_lms in /Users/kylemaurer/Documents/Websites/plugins.dev/wp-content/plugins/learndash/includes/ld-autoupdate.php on line 12."

- It seems that you have an issue in the learn-dash itself not our plugin, so kindly provide the wordpress access or Cpanel access in order to check it at your side.

**Comment by objectsweb** [comment]
Reminder..

**Comment by brashrebel** [comment]
Sorry about this. It was a mistake on my part.

**Comment by objectsweb** [comment]
- Never mind.
